### ISSUE TITLE
issue 1st 🎉

### ISSUE THREAD

**Issue by efkan** [themaximal1st/vectordb.js#1]
I can't believe this repo still doesn't have an issue. You've made it great!  

I wonder how I can get all the records from DB.

If I pass an empty string with the purpose of getting all documents from the db, it throws the error of `Error: input must be a string`.

The piece of code I execute:

<img width="484" alt="image" src="https://github.com/themaximal1st/vectordb.js/assets/6974198/4ef3c921-f9ac-4b30-acf1-557720a703c3">

**Comment by themaximalist** [comment]
Thanks @efkan! The best way to get all records is probably by accessing the internal inputs, rather than searching. Something like this should work

```javascript
for (let i = 0; i < vectorStore.inputs.length; i++) {
    console.log("INPUT", i, vectorStore.inputs[i]);
    console.log("OBJECTS", i, vectorStore.objects[i]);
}
```

If this turns out to be a common case I can add a helper like `vectorStore.all()` that returns these automatically.

Please let me know if this doesn't work for you!
